language: fr
title: Cookie-Richtlinie
text: Wir verwenden Cookies, um Ihnen einen optimalen Service anzubieten und diesen immer weiter zu verbessern. Weitere Informationen finden Sie in unserer Datenschutzerklärung.
private_policy_link: /privatePolicy
first_button_text: btn1
second_button_text: btn2
background_color: blue
color: white

block:
  block_1:
    check: true
    title: Notwendig
    text: Diese Cookies sind notwendig, um die Kernfunktionen dieser Webseite, wie etwa sicherheitsrelevante Funktionen, auszuführen. Mit diesen Cookies können wir auch erkennen, ob Sie in Ihrem Profil angemeldet bleiben möchten, um Ihnen beim erneuten Besuch unserer Webseite einen schnellen Zugang zu unseren Dienstleistungen zu ermöglichen.
  block_2:
    check: false
    title: Performance
    text: Um unsere Webseite kontinuierlich zu verbessern, verfolgen wir Daten für statistische und analytische Zwecke. Mit diesen Cookies messen wir zum Beispiel, wie häufig Benutzer wiederkehren und welche Funktionen sie verwenden.
  block_3:
    check: false
    title: Komfort
    text: Wir verwenden diese Cookies, um die Nutzung unserer Webseite für Sie komfortabler zu gestalten. Beispielsweise merken wir uns, welche Bereiche der Webseite Sie bereits besucht haben und können Ihnen dadurch helfen, die Webseite optimal zu nutzen.
  block_4:
    check: false
    title: Marketing
    text: Diese Cookies und Anfragen an Drittdienste werden verwendet, um Werbung zu schalten, die besser auf Sie und Ihre Interessen zugeschnitten ist. Sie können außerdem eingesetzt werden, um die Häufigkeit zu begrenzen, mit der Sie eine Anzeige sehen, und um die Wirksamkeit von Werbekampagnen zu messen.
